name: Unit Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [main]
    tags-ignore: ["**"]

env:
  GO_VERSION_FILE: "go.mod"
  CHECK_LATEST: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          check-latest: ${{ env.CHECK_LATEST }}
      - 
        name: Pull dependencies
        run: go mod vendor
      - 
        name: Linter
        run: make lint
      - 
        name: Unit tests
        run: make test
      - 
        name: Vulnerability scan
        run: make vulncheck
  
  version:
    name: Version
    concurrency: tagging
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Calculate semver tag
        id: semver-tag
        uses: snapfi/semver-action@main
      - 
        name: Create tag
        uses: actions/github-script@v6
        if: steps.semver-tag.outputs.semver_tag != ''
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver-tag.outputs.semver_tag }}",
              sha: context.sha
            })
